version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: sca_db
      MYSQL_USER: sca_user
      MYSQL_PASSWORD: scaStrong#2025!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sca_v1.sql:/docker-entrypoint-initdb.d/01-ddl.sql
    networks:
      - sca-network
    restart: always

  backend:
    image: sca-be:latest
    container_name: sca-be
    ports:
      - "8081:8080"  # Jenkins 충돌 방지
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sca-network
    depends_on:
      - mysql

  frontend:
    image: sca-fe:latest
    container_name: sca-fe
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - sca-network
    depends_on:
      - backend

networks:
  sca-network:
    driver: bridge

volumes:
  mysql-data:
